function MFTM_v2_plot(ACC_mean, ACC_se, ACC_predicted, RT_mean, RT_se)%, Eff_mean, Eff_se)
%
% This function is used to make the plots for the emprical and predicted 
% accuracy, RT, and efficiency results for the MFTM (5-arrow version). 
%
% Tingting Wu wrote it 08/19/2015
%
% --------------------------------
% Inputs:
% Each input has to be in a 3(congruency: 3:2, 4:1, 5:0) x 4 (SOA: 250,500,
% 1000, 2000 ms) array. 
% - ACC_mean: mean accuracy in each condition.
% - ACC_se:   standard error of the accuracy in each condition. No error
%             bar if it is empty.
% - ACC_predicted: predicted accuracy in each condition.
% - RT_mean: mean RT in each condition.
% - RT_se:   standard error of the RT in each condition. No error
%             bar if it is empty.
% - Eff_mean: mean efficiency in each condition.
% - Eff_se:   standard error of the efficiency in each condition. No error
%             bar if it is empty.
% ---------------------------------
%
% Example:
% To visualize single subject's results, use this function directly after running the
% "MFTM3_Capacity_MLE" function, as:
% MFTM3_plot(ACC_mean, [], ACC_predicted, RT_mean, [], Eff_mean, [])
%
% To visualize the group results, please compute the group mean accuracy as
% "ACC_mean", with m columns for ArrowRatio (3:2, 4:1, 5:0) and n rows for
% exposure time (250, 500, 1000, 2000 ms) (same input format for the following
% variables), and the group standard error(SE) of accuracy as "ACC_se", group
% mean predicted accuracy as "ACC_predicted", group mean and SE of RT as "RT_mean" and "RT_se", and group mean and SE of
% efficiency as "Eff_mean" and "Eff_se". Then run:
% MFTM3_plot(ACC_mean, ACC_se, ACC_predicted, RT_mean, RT_se, Eff_mean, Eff_se)

    %% Experiment parameters
    setCondition = {'3:2','4:1','5:0'};
    SOAs = [250, 500, 1000, 2000];

    %% Plot parameters
    colors2 = [.2 .6 1; .5  0 .8;  1  0 .2];
    linestyles = {'-','-','-'};

    %% Plot figures
    figure; hold on;
    % Emprical accuracy
    subplot(1,3,1)
    for i = 1 : length(setCondition)
        if isempty(ACC_se)
            mkMFTMplot(SOAs, ACC_mean(i,:)*100,colors2(i,:),linestyles{i});
        else
            mkMFTMerrorbar(SOAs,ACC_mean(i,:)*100,ACC_se(i,:)*100,colors2(i,:),linestyles{i});
        end
        hold on;
    end
    ylim([min(floor(min(min(ACC_mean * 100))/10)*10,50), ...
        ceil(max(max(ACC_mean * 100))/10)*10 + 10]); 
    set(gca,'Ytick',[50 60 70 80 90 100]);
    axis('square'); box('off');
    mkMFTMaxis('Empirical Accuracy (%)',SOAs);

    % Predicted accuracy
    subplot(1,3,2);
    for i = 1 : length(setCondition)
        mkMFTMplot(SOAs, ACC_predicted(i,:)*100,colors2(i,:),linestyles{i});
        hold on;
    end
    mkMFTMaxis('Predicted Accuracy (%)',SOAs);
    ylim([min(floor(min(min(ACC_predicted * 100))/10)*10,50), ...
        ceil(max(max(ACC_predicted * 100))/10)*10 + 10]); 
    set(gca,'Ytick',[50 60 70 80 90 100]);
    axis('square'); box('off');
    legend(setCondition,'Location','Best','FontSize',10,'FontName','Arial');
    
    % RT
    subplot(1,3,3)
    for i = 1 : length(setCondition)
        if isempty(RT_se)
            mkMFTMplot(SOAs, RT_mean(i,:),colors2(i,:),linestyles{i});
        else
            mkMFTMerrorbar(SOAs,RT_mean(i,:),RT_se(i,:),colors2(i,:),linestyles{i});
        end
        hold on;
    end
    axis('square'); box('off');
    mkMFTMaxis('RT (ms)',SOAs);
    
% 
%     % Efficiency
%     subplot(2,2,4);
%     for i = 1 : length(setCondition)
%         if isempty(Eff_se)
%             mkMFTMplot(SOAs, Eff_mean(i,:),colors2(i,:),linestyles{i});
%         else
%             mkMFTMerrorbar(SOAs,Eff_mean(i,:),Eff_se(i,:),colors2(i,:),linestyles{i});
%         end
%         hold on;
%     end
%     mkMFTMaxis('Efficiency',SOAs);
end

function mkMFTMplot(X,Y, color, style)
    plot(X,Y, 'MarkerSize',8,'MarkerSize',8,'MarkerFaceColor',color,'Marker','o',...
        'LineStyle',style,'LineWidth',1.5,'Color',color);
end

function mkMFTMerrorbar(X, Y, E, color,style)
    %CREATEFIGURE(X1, Y1, E1)
    %  X:  X
    %  Y:  Y
    %  E:  errorbar of Y
    %  color: error bar line and marker color, RGB coding
    %  style: line style, '-' or '--'
    %  Auto-generated by MATLAB on 21-Oct-2014 16:21:05
    % wtt revised it 10/21/2014

    % Create errorbar
    errorbar(X,Y,E,'MarkerSize',8,'MarkerFaceColor',color,'Marker','o',...
        'LineStyle',style,'LineWidth',1.5,'Color',color);
end

function mkMFTMaxis(ylabel_name,x_tick)
    xlim ([0 2200]); set(gca,'xtick', x_tick);
    xlabel('SOA (ms)','FontSize',10,'FontName','Arial')
    ylabel(ylabel_name,'FontSize',10,'FontName','Arial');
end